### ISSUE TITLE
Address failing workflows

### ISSUE THREAD

**Issue by macb500** [uoy-trials/library-redcap-api#7]
https://github.com/uoy-trials/library-redcap-api/actions

**Comment by tp1045** [comment]
https://github.com/orgs/community/discussions/26256

**Comment by tp1045** [comment]
Remove old workflow runs using Powershell:

-- Get all the workflows
`gh api -X GET /repos/uoy-trials/library-redcap-api/actions/runs`

![image](https://github.com/uoy-trials/library-redcap-api/assets/82442785/52d6c5d8-0720-4e82-9932-ca11515dc1e6)

save runs to delete, id here is specific to the "Publish nuget package.." workflow 

`$legacyRuns = gh api -X GET /repos/uoy-trials/library-redcap-api/actions/workflows/77110303/runs | jq '.workflow_runs[] | .id'`

delete em
`foreach ($run in $legacyRuns) { gh api -X DELETE /repos/uoy-trials/library-redcap-api/actions/runs/$run }`

clean as a whistle (are whistles clean?) 

![image](https://github.com/uoy-trials/library-redcap-api/assets/82442785/8b6da3a3-b178-4537-b88f-787391e6a47a)
